[env:adafruit_feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino

build_flags =
    -DBILGE_MONITOR
    -DDEBUG_SERIAL
    -I../shared-lib/include

lib_deps =
    file://../shared-lib

monitor_speed = 115200
